//
// AddressBookItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct AddressBookItem: Codable {

    public enum Currency: String, Codable {
        case btc = "BTC"
        case eth = "ETH"
    }
    public enum ModelType: String, Codable {
        case transfer = "transfer"
        case withdrawal = "withdrawal"
    }
    /** Currency, i.e &#x60;\&quot;BTC\&quot;&#x60;, &#x60;\&quot;ETH\&quot;&#x60; */
    public var currency: Currency
    /** Address in proper format for currency */
    public var address: String
    /** Address book type */
    public var type: ModelType?
    /** The timestamp (seconds since the Unix epoch, with millisecond precision) */
    public var creationTimestamp: Int

    public init(currency: Currency, address: String, type: ModelType?, creationTimestamp: Int) {
        self.currency = currency
        self.address = address
        self.type = type
        self.creationTimestamp = creationTimestamp
    }

    public enum CodingKeys: String, CodingKey { 
        case currency
        case address
        case type
        case creationTimestamp = "creation_timestamp"
    }


}

