//
// Currency.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Currency: Codable {

    public enum CoinType: String, Codable {
        case bitcoin = "BITCOIN"
        case ether = "ETHER"
    }
    /** Minimum number of block chain confirmations before deposit is accepted. */
    public var minConfirmations: Int?
    /** The minimum transaction fee paid for withdrawals */
    public var minWithdrawalFee: Double?
    /** False if deposit address creation is disabled */
    public var disabledDepositAddressCreation: Bool?
    /** The abbreviation of the currency. This abbreviation is used elsewhere in the API to identify the currency. */
    public var currency: String
    /** The full name for the currency. */
    public var currencyLong: String
    /** The total transaction fee paid for withdrawals */
    public var withdrawalFee: Double
    /** fee precision */
    public var feePrecision: Int?
    public var withdrawalPriorities: [CurrencyWithdrawalPriorities]?
    /** The type of the currency. */
    public var coinType: CoinType

    public init(minConfirmations: Int?, minWithdrawalFee: Double?, disabledDepositAddressCreation: Bool?, currency: String, currencyLong: String, withdrawalFee: Double, feePrecision: Int?, withdrawalPriorities: [CurrencyWithdrawalPriorities]?, coinType: CoinType) {
        self.minConfirmations = minConfirmations
        self.minWithdrawalFee = minWithdrawalFee
        self.disabledDepositAddressCreation = disabledDepositAddressCreation
        self.currency = currency
        self.currencyLong = currencyLong
        self.withdrawalFee = withdrawalFee
        self.feePrecision = feePrecision
        self.withdrawalPriorities = withdrawalPriorities
        self.coinType = coinType
    }

    public enum CodingKeys: String, CodingKey { 
        case minConfirmations = "min_confirmations"
        case minWithdrawalFee = "min_withdrawal_fee"
        case disabledDepositAddressCreation = "disabled_deposit_address_creation"
        case currency
        case currencyLong = "currency_long"
        case withdrawalFee = "withdrawal_fee"
        case feePrecision = "fee_precision"
        case withdrawalPriorities = "withdrawal_priorities"
        case coinType = "coin_type"
    }


}

