//
// CurrencyWithdrawalPriorities.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CurrencyWithdrawalPriorities: Codable {

    public var name: String
    public var value: Double

    public init(name: String, value: Double) {
        self.name = name
        self.value = value
    }


}

