//
// CurrencyPortfolio.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct CurrencyPortfolio: Codable {

    public enum Currency: String, Codable {
        case btc = "btc"
        case eth = "eth"
    }
    public var maintenanceMargin: Double
    public var availableWithdrawalFunds: Double
    public var initialMargin: Double
    public var availableFunds: Double
    public var currency: Currency
    public var marginBalance: Double
    public var equity: Double
    public var balance: Double

    public init(maintenanceMargin: Double, availableWithdrawalFunds: Double, initialMargin: Double, availableFunds: Double, currency: Currency, marginBalance: Double, equity: Double, balance: Double) {
        self.maintenanceMargin = maintenanceMargin
        self.availableWithdrawalFunds = availableWithdrawalFunds
        self.initialMargin = initialMargin
        self.availableFunds = availableFunds
        self.currency = currency
        self.marginBalance = marginBalance
        self.equity = equity
        self.balance = balance
    }

    public enum CodingKeys: String, CodingKey { 
        case maintenanceMargin = "maintenance_margin"
        case availableWithdrawalFunds = "available_withdrawal_funds"
        case initialMargin = "initial_margin"
        case availableFunds = "available_funds"
        case currency
        case marginBalance = "margin_balance"
        case equity
        case balance
    }


}

