//
// OrderIdInitialMarginPair.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct OrderIdInitialMarginPair: Codable {

    /** Unique order identifier */
    public var orderId: String
    /** Initial margin of order, in base currency */
    public var initialMargin: Double

    public init(orderId: String, initialMargin: Double) {
        self.orderId = orderId
        self.initialMargin = initialMargin
    }

    public enum CodingKeys: String, CodingKey { 
        case orderId = "order_id"
        case initialMargin = "initial_margin"
    }


}

