//
// Portfolio.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Portfolio: Codable {

    public var eth: PortfolioEth
    public var btc: PortfolioEth

    public init(eth: PortfolioEth, btc: PortfolioEth) {
        self.eth = eth
        self.btc = btc
    }


}

