//
// PublicTrade.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PublicTrade: Codable {

    public enum Direction: String, Codable {
        case buy = "buy"
        case sell = "sell"
    }
    public enum TickDirection: Int, Codable {
        case _0 = 0
        case _1 = 1
        case _2 = 2
        case _3 = 3
    }
    /** Trade direction of the taker */
    public var direction: Direction
    /** Direction of the \&quot;tick\&quot; (&#x60;0&#x60; &#x3D; Plus Tick, &#x60;1&#x60; &#x3D; Zero-Plus Tick, &#x60;2&#x60; &#x3D; Minus Tick, &#x60;3&#x60; &#x3D; Zero-Minus Tick). */
    public var tickDirection: TickDirection
    /** The timestamp of the trade */
    public var timestamp: Int
    /** The price of the trade */
    public var price: Double
    /** The sequence number of the trade within instrument */
    public var tradeSeq: Int
    /** Unique (per currency) trade identifier */
    public var tradeId: String
    /** Option implied volatility for the price (Option only) */
    public var iv: Double?
    /** Index Price at the moment of trade */
    public var indexPrice: Double
    /** Trade amount. For perpetual and futures - in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH. */
    public var amount: Double
    /** Unique instrument identifier */
    public var instrumentName: String

    public init(direction: Direction, tickDirection: TickDirection, timestamp: Int, price: Double, tradeSeq: Int, tradeId: String, iv: Double?, indexPrice: Double, amount: Double, instrumentName: String) {
        self.direction = direction
        self.tickDirection = tickDirection
        self.timestamp = timestamp
        self.price = price
        self.tradeSeq = tradeSeq
        self.tradeId = tradeId
        self.iv = iv
        self.indexPrice = indexPrice
        self.amount = amount
        self.instrumentName = instrumentName
    }

    public enum CodingKeys: String, CodingKey { 
        case direction
        case tickDirection = "tick_direction"
        case timestamp
        case price
        case tradeSeq = "trade_seq"
        case tradeId = "trade_id"
        case iv
        case indexPrice = "index_price"
        case amount
        case instrumentName = "instrument_name"
    }


}

