//
// TradesVolumes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TradesVolumes: Codable {

    public enum CurrencyPair: String, Codable {
        case btcUsd = "btc_usd"
        case ethUsd = "eth_usd"
    }
    /** Total 24h trade volume for call options. This is expressed in the base currency, e.g. BTC for &#x60;btc_usd&#x60; */
    public var callsVolume: Double
    /** Total 24h trade volume for put options. This is expressed in the base currency, e.g. BTC for &#x60;btc_usd&#x60; */
    public var putsVolume: Double
    /** Currency pair: &#x60;\&quot;btc_usd\&quot;&#x60; or &#x60;\&quot;eth_usd\&quot;&#x60; */
    public var currencyPair: CurrencyPair
    /** Total 24h trade volume for futures. This is expressed in the base currency, e.g. BTC for &#x60;btc_usd&#x60; */
    public var futuresVolume: Double

    public init(callsVolume: Double, putsVolume: Double, currencyPair: CurrencyPair, futuresVolume: Double) {
        self.callsVolume = callsVolume
        self.putsVolume = putsVolume
        self.currencyPair = currencyPair
        self.futuresVolume = futuresVolume
    }

    public enum CodingKeys: String, CodingKey { 
        case callsVolume = "calls_volume"
        case putsVolume = "puts_volume"
        case currencyPair = "currency_pair"
        case futuresVolume = "futures_volume"
    }


}

