# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Currency")

model.instance <- Currency$new()

test_that("min_confirmations", {
  # tests for the property `min_confirmations` (integer)
  # Minimum number of block chain confirmations before deposit is accepted.

  # uncomment below to test the property 
  #expect_equal(model.instance$`min_confirmations`, "EXPECTED_RESULT")
})

test_that("min_withdrawal_fee", {
  # tests for the property `min_withdrawal_fee` (numeric)
  # The minimum transaction fee paid for withdrawals

  # uncomment below to test the property 
  #expect_equal(model.instance$`min_withdrawal_fee`, "EXPECTED_RESULT")
})

test_that("disabled_deposit_address_creation", {
  # tests for the property `disabled_deposit_address_creation` (character)
  # False if deposit address creation is disabled

  # uncomment below to test the property 
  #expect_equal(model.instance$`disabled_deposit_address_creation`, "EXPECTED_RESULT")
})

test_that("currency", {
  # tests for the property `currency` (character)
  # The abbreviation of the currency. This abbreviation is used elsewhere in the API to identify the currency.

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency`, "EXPECTED_RESULT")
})

test_that("currency_long", {
  # tests for the property `currency_long` (character)
  # The full name for the currency.

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency_long`, "EXPECTED_RESULT")
})

test_that("withdrawal_fee", {
  # tests for the property `withdrawal_fee` (numeric)
  # The total transaction fee paid for withdrawals

  # uncomment below to test the property 
  #expect_equal(model.instance$`withdrawal_fee`, "EXPECTED_RESULT")
})

test_that("fee_precision", {
  # tests for the property `fee_precision` (integer)
  # fee precision

  # uncomment below to test the property 
  #expect_equal(model.instance$`fee_precision`, "EXPECTED_RESULT")
})

test_that("withdrawal_priorities", {
  # tests for the property `withdrawal_priorities` (CurrencyWithdrawalPriorities)

  # uncomment below to test the property 
  #expect_equal(model.instance$`withdrawal_priorities`, "EXPECTED_RESULT")
})

test_that("coin_type", {
  # tests for the property `coin_type` (character)
  # The type of the currency.

  # uncomment below to test the property 
  #expect_equal(model.instance$`coin_type`, "EXPECTED_RESULT")
})

