# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WalletApi")

api.instance <- WalletApi$new()

test_that("PrivateAddToAddressBookGet", {
  # tests for PrivateAddToAddressBookGet
  # base path: https://www.deribit.com/api/v2
  # Adds new entry to address book of given type
  # @param character  currency  The currency symbol 
  # @param character  type  Address book type 
  # @param character  address  Address in currency format, it must be in address book 
  # @param character  name  Name of address book entry 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCancelTransferByIdGet", {
  # tests for PrivateCancelTransferByIdGet
  # base path: https://www.deribit.com/api/v2
  # Cancel transfer
  # @param character  currency  The currency symbol 
  # @param integer  id  Id of transfer 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCancelWithdrawalGet", {
  # tests for PrivateCancelWithdrawalGet
  # base path: https://www.deribit.com/api/v2
  # Cancels withdrawal request
  # @param character  currency  The currency symbol 
  # @param numeric  id  The withdrawal id 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCreateDepositAddressGet", {
  # tests for PrivateCreateDepositAddressGet
  # base path: https://www.deribit.com/api/v2
  # Creates deposit address in currency
  # @param character  currency  The currency symbol 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetAddressBookGet", {
  # tests for PrivateGetAddressBookGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves address book of given type
  # @param character  currency  The currency symbol 
  # @param character  type  Address book type 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetCurrentDepositAddressGet", {
  # tests for PrivateGetCurrentDepositAddressGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve deposit address for currency
  # @param character  currency  The currency symbol 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetDepositsGet", {
  # tests for PrivateGetDepositsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest users deposits
  # @param character  currency  The currency symbol 
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param integer  offset  The offset for pagination, default - `0`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetTransfersGet", {
  # tests for PrivateGetTransfersGet
  # base path: https://www.deribit.com/api/v2
  # Adds new entry to address book of given type
  # @param character  currency  The currency symbol 
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param integer  offset  The offset for pagination, default - `0`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetWithdrawalsGet", {
  # tests for PrivateGetWithdrawalsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest users withdrawals
  # @param character  currency  The currency symbol 
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param integer  offset  The offset for pagination, default - `0`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateRemoveFromAddressBookGet", {
  # tests for PrivateRemoveFromAddressBookGet
  # base path: https://www.deribit.com/api/v2
  # Adds new entry to address book of given type
  # @param character  currency  The currency symbol 
  # @param character  type  Address book type 
  # @param character  address  Address in currency format, it must be in address book 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSubmitTransferToSubaccountGet", {
  # tests for PrivateSubmitTransferToSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Transfer funds to a subaccount.
  # @param character  currency  The currency symbol 
  # @param numeric  amount  Amount of funds to be transferred 
  # @param integer  destination  Id of destination subaccount 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSubmitTransferToUserGet", {
  # tests for PrivateSubmitTransferToUserGet
  # base path: https://www.deribit.com/api/v2
  # Transfer funds to a another user.
  # @param character  currency  The currency symbol 
  # @param numeric  amount  Amount of funds to be transferred 
  # @param character  destination  Destination address from address book 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateToggleDepositAddressCreationGet", {
  # tests for PrivateToggleDepositAddressCreationGet
  # base path: https://www.deribit.com/api/v2
  # Enable or disable deposit address creation
  # @param character  currency  The currency symbol 
  # @param character  state   
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateWithdrawGet", {
  # tests for PrivateWithdrawGet
  # base path: https://www.deribit.com/api/v2
  # Creates a new withdrawal request
  # @param character  currency  The currency symbol 
  # @param character  address  Address in currency format, it must be in address book 
  # @param numeric  amount  Amount of funds to be withdrawn 
  # @param character  priority  Withdrawal priority, optional for BTC, default: `high`  (optional)
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

