# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TransferItem")

model.instance <- TransferItem$new()

test_that("updated_timestamp", {
  # tests for the property `updated_timestamp` (integer)
  # The timestamp (seconds since the Unix epoch, with millisecond precision)

  # uncomment below to test the property 
  #expect_equal(model.instance$`updated_timestamp`, "EXPECTED_RESULT")
})

test_that("direction", {
  # tests for the property `direction` (character)
  # Transfer direction

  # uncomment below to test the property 
  #expect_equal(model.instance$`direction`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (numeric)
  # Amount of funds in given currency

  # uncomment below to test the property 
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("other_side", {
  # tests for the property `other_side` (character)
  # For transfer from/to subaccount returns this subaccount name, for transfer to other account returns address, for transfer from other account returns that accounts username.

  # uncomment below to test the property 
  #expect_equal(model.instance$`other_side`, "EXPECTED_RESULT")
})

test_that("currency", {
  # tests for the property `currency` (character)
  # Currency, i.e &#x60;\&quot;BTC\&quot;&#x60;, &#x60;\&quot;ETH\&quot;&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency`, "EXPECTED_RESULT")
})

test_that("state", {
  # tests for the property `state` (character)
  # Transfer state, allowed values : &#x60;prepared&#x60;, &#x60;confirmed&#x60;, &#x60;cancelled&#x60;, &#x60;waiting_for_admin&#x60;, &#x60;rejection_reason&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

test_that("created_timestamp", {
  # tests for the property `created_timestamp` (integer)
  # The timestamp (seconds since the Unix epoch, with millisecond precision)

  # uncomment below to test the property 
  #expect_equal(model.instance$`created_timestamp`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # Type of transfer: &#x60;user&#x60; - sent to user, &#x60;subaccount&#x60; - sent to subaccount

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)
  # Id of transfer

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

