# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CurrencyPortfolio")

model.instance <- CurrencyPortfolio$new()

test_that("maintenance_margin", {
  # tests for the property `maintenance_margin` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`maintenance_margin`, "EXPECTED_RESULT")
})

test_that("available_withdrawal_funds", {
  # tests for the property `available_withdrawal_funds` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`available_withdrawal_funds`, "EXPECTED_RESULT")
})

test_that("initial_margin", {
  # tests for the property `initial_margin` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`initial_margin`, "EXPECTED_RESULT")
})

test_that("available_funds", {
  # tests for the property `available_funds` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`available_funds`, "EXPECTED_RESULT")
})

test_that("currency", {
  # tests for the property `currency` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency`, "EXPECTED_RESULT")
})

test_that("margin_balance", {
  # tests for the property `margin_balance` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`margin_balance`, "EXPECTED_RESULT")
})

test_that("equity", {
  # tests for the property `equity` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`equity`, "EXPECTED_RESULT")
})

test_that("balance", {
  # tests for the property `balance` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`balance`, "EXPECTED_RESULT")
})

