# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Position")

model.instance <- Position$new()

test_that("direction", {
  # tests for the property `direction` (character)
  # direction, &#x60;buy&#x60; or &#x60;sell&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`direction`, "EXPECTED_RESULT")
})

test_that("average_price_usd", {
  # tests for the property `average_price_usd` (numeric)
  # Only for options, average price in USD

  # uncomment below to test the property 
  #expect_equal(model.instance$`average_price_usd`, "EXPECTED_RESULT")
})

test_that("estimated_liquidation_price", {
  # tests for the property `estimated_liquidation_price` (numeric)
  # Only for futures, estimated liquidation price

  # uncomment below to test the property 
  #expect_equal(model.instance$`estimated_liquidation_price`, "EXPECTED_RESULT")
})

test_that("floating_profit_loss", {
  # tests for the property `floating_profit_loss` (numeric)
  # Floating profit or loss

  # uncomment below to test the property 
  #expect_equal(model.instance$`floating_profit_loss`, "EXPECTED_RESULT")
})

test_that("floating_profit_loss_usd", {
  # tests for the property `floating_profit_loss_usd` (numeric)
  # Only for options, floating profit or loss in USD

  # uncomment below to test the property 
  #expect_equal(model.instance$`floating_profit_loss_usd`, "EXPECTED_RESULT")
})

test_that("open_orders_margin", {
  # tests for the property `open_orders_margin` (numeric)
  # Open orders margin

  # uncomment below to test the property 
  #expect_equal(model.instance$`open_orders_margin`, "EXPECTED_RESULT")
})

test_that("total_profit_loss", {
  # tests for the property `total_profit_loss` (numeric)
  # Profit or loss from position

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_profit_loss`, "EXPECTED_RESULT")
})

test_that("realized_profit_loss", {
  # tests for the property `realized_profit_loss` (numeric)
  # Realized profit or loss

  # uncomment below to test the property 
  #expect_equal(model.instance$`realized_profit_loss`, "EXPECTED_RESULT")
})

test_that("delta", {
  # tests for the property `delta` (numeric)
  # Delta parameter

  # uncomment below to test the property 
  #expect_equal(model.instance$`delta`, "EXPECTED_RESULT")
})

test_that("initial_margin", {
  # tests for the property `initial_margin` (numeric)
  # Initial margin

  # uncomment below to test the property 
  #expect_equal(model.instance$`initial_margin`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (numeric)
  # Position size for futures size in quote currency (e.g. USD), for options size is in base currency (e.g. BTC)

  # uncomment below to test the property 
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("maintenance_margin", {
  # tests for the property `maintenance_margin` (numeric)
  # Maintenance margin

  # uncomment below to test the property 
  #expect_equal(model.instance$`maintenance_margin`, "EXPECTED_RESULT")
})

test_that("kind", {
  # tests for the property `kind` (character)
  # Instrument kind, &#x60;\&quot;future\&quot;&#x60; or &#x60;\&quot;option\&quot;&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`kind`, "EXPECTED_RESULT")
})

test_that("mark_price", {
  # tests for the property `mark_price` (numeric)
  # Current mark price for position&#39;s instrument

  # uncomment below to test the property 
  #expect_equal(model.instance$`mark_price`, "EXPECTED_RESULT")
})

test_that("average_price", {
  # tests for the property `average_price` (numeric)
  # Average price of trades that built this position

  # uncomment below to test the property 
  #expect_equal(model.instance$`average_price`, "EXPECTED_RESULT")
})

test_that("settlement_price", {
  # tests for the property `settlement_price` (numeric)
  # Last settlement price for position&#39;s instrument 0 if instrument wasn&#39;t settled yet

  # uncomment below to test the property 
  #expect_equal(model.instance$`settlement_price`, "EXPECTED_RESULT")
})

test_that("index_price", {
  # tests for the property `index_price` (numeric)
  # Current index price

  # uncomment below to test the property 
  #expect_equal(model.instance$`index_price`, "EXPECTED_RESULT")
})

test_that("instrument_name", {
  # tests for the property `instrument_name` (character)
  # Unique instrument identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`instrument_name`, "EXPECTED_RESULT")
})

test_that("size_currency", {
  # tests for the property `size_currency` (numeric)
  # Only for futures, position size in base currency

  # uncomment below to test the property 
  #expect_equal(model.instance$`size_currency`, "EXPECTED_RESULT")
})

