# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubscriptionManagementApi")

api.instance <- SubscriptionManagementApi$new()

test_that("PrivateSubscribeGet", {
  # tests for PrivateSubscribeGet
  # base path: https://www.deribit.com/api/v2
  # Subscribe to one or more channels.
  # Subscribe to one or more channels.  The name of the channel determines what information will be provided, and in what form. 
  # @param character  channels  A list of channels to subscribe to. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateUnsubscribeGet", {
  # tests for PrivateUnsubscribeGet
  # base path: https://www.deribit.com/api/v2
  # Unsubscribe from one or more channels.
  # @param character  channels  A list of channels to unsubscribe from. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicSubscribeGet", {
  # tests for PublicSubscribeGet
  # base path: https://www.deribit.com/api/v2
  # Subscribe to one or more channels.
  # Subscribe to one or more channels.  This is the same method as [/private/subscribe](#private_subscribe), but it can only be used for &#39;public&#39; channels. 
  # @param character  channels  A list of channels to subscribe to. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicUnsubscribeGet", {
  # tests for PublicUnsubscribeGet
  # base path: https://www.deribit.com/api/v2
  # Unsubscribe from one or more channels.
  # @param character  channels  A list of channels to unsubscribe from. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

