# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SupportingApi")

api.instance <- SupportingApi$new()

test_that("PublicGetTimeGet", {
  # tests for PublicGetTimeGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves the current time (in milliseconds). This API endpoint can be used to check the clock skew between your software and Deribit&#39;s systems.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicTestGet", {
  # tests for PublicTestGet
  # base path: https://www.deribit.com/api/v2
  # Tests the connection to the API server, and returns its version. You can use this to make sure the API is reachable, and matches the expected version.
  # @param character  expected.result  The value \"exception\" will trigger an error response. This may be useful for testing wrapper libraries.  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

