# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Settlement")

model.instance <- Settlement$new()

test_that("session_profit_loss", {
  # tests for the property `session_profit_loss` (numeric)
  # total value of session profit and losses (in base currency)

  # uncomment below to test the property 
  #expect_equal(model.instance$`session_profit_loss`, "EXPECTED_RESULT")
})

test_that("mark_price", {
  # tests for the property `mark_price` (numeric)
  # mark price for at the settlement time (in quote currency; settlement and delivery only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`mark_price`, "EXPECTED_RESULT")
})

test_that("funding", {
  # tests for the property `funding` (numeric)
  # funding (in base currency ; settlement for perpetual product only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`funding`, "EXPECTED_RESULT")
})

test_that("socialized", {
  # tests for the property `socialized` (numeric)
  # the amount of the socialized losses (in base currency; bankruptcy only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`socialized`, "EXPECTED_RESULT")
})

test_that("session_bankrupcy", {
  # tests for the property `session_bankrupcy` (numeric)
  # value of session bankrupcy (in base currency; bankruptcy only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`session_bankrupcy`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (integer)
  # The timestamp (seconds since the Unix epoch, with millisecond precision)

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("profit_loss", {
  # tests for the property `profit_loss` (numeric)
  # profit and loss (in base currency; settlement and delivery only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`profit_loss`, "EXPECTED_RESULT")
})

test_that("funded", {
  # tests for the property `funded` (numeric)
  # funded amount (bankruptcy only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`funded`, "EXPECTED_RESULT")
})

test_that("index_price", {
  # tests for the property `index_price` (numeric)
  # underlying index price at time of event (in quote currency; settlement and delivery only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`index_price`, "EXPECTED_RESULT")
})

test_that("session_tax", {
  # tests for the property `session_tax` (numeric)
  # total amount of paid taxes/fees (in base currency; bankruptcy only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`session_tax`, "EXPECTED_RESULT")
})

test_that("session_tax_rate", {
  # tests for the property `session_tax_rate` (numeric)
  # rate of paid texes/fees (in base currency; bankruptcy only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`session_tax_rate`, "EXPECTED_RESULT")
})

test_that("instrument_name", {
  # tests for the property `instrument_name` (character)
  # instrument name (settlement and delivery only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`instrument_name`, "EXPECTED_RESULT")
})

test_that("position", {
  # tests for the property `position` (numeric)
  # position size (in quote currency; settlement and delivery only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`position`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # The type of settlement. &#x60;settlement&#x60;, &#x60;delivery&#x60; or &#x60;bankruptcy&#x60;.

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

