# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserTrade")

model.instance <- UserTrade$new()

test_that("direction", {
  # tests for the property `direction` (character)
  # Trade direction of the taker

  # uncomment below to test the property 
  #expect_equal(model.instance$`direction`, "EXPECTED_RESULT")
})

test_that("fee_currency", {
  # tests for the property `fee_currency` (character)
  # Currency, i.e &#x60;\&quot;BTC\&quot;&#x60;, &#x60;\&quot;ETH\&quot;&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`fee_currency`, "EXPECTED_RESULT")
})

test_that("order_id", {
  # tests for the property `order_id` (character)
  # Id of the user order (maker or taker), i.e. subscriber&#39;s order id that took part in the trade

  # uncomment below to test the property 
  #expect_equal(model.instance$`order_id`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (integer)
  # The timestamp of the trade

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("price", {
  # tests for the property `price` (numeric)
  # The price of the trade

  # uncomment below to test the property 
  #expect_equal(model.instance$`price`, "EXPECTED_RESULT")
})

test_that("iv", {
  # tests for the property `iv` (numeric)
  # Option implied volatility for the price (Option only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`iv`, "EXPECTED_RESULT")
})

test_that("trade_id", {
  # tests for the property `trade_id` (character)
  # Unique (per currency) trade identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`trade_id`, "EXPECTED_RESULT")
})

test_that("fee", {
  # tests for the property `fee` (numeric)
  # User&#39;s fee in units of the specified &#x60;fee_currency&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`fee`, "EXPECTED_RESULT")
})

test_that("order_type", {
  # tests for the property `order_type` (character)
  # Order type: &#x60;\&quot;limit&#x60;, &#x60;\&quot;market\&quot;&#x60;, or &#x60;\&quot;liquidation\&quot;&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`order_type`, "EXPECTED_RESULT")
})

test_that("trade_seq", {
  # tests for the property `trade_seq` (integer)
  # The sequence number of the trade within instrument

  # uncomment below to test the property 
  #expect_equal(model.instance$`trade_seq`, "EXPECTED_RESULT")
})

test_that("self_trade", {
  # tests for the property `self_trade` (character)
  # &#x60;true&#x60; if the trade is against own order. This can only happen when your account has self-trading enabled. Contact an administrator if you think you need that

  # uncomment below to test the property 
  #expect_equal(model.instance$`self_trade`, "EXPECTED_RESULT")
})

test_that("state", {
  # tests for the property `state` (character)
  # order state, &#x60;\&quot;open\&quot;&#x60;, &#x60;\&quot;filled\&quot;&#x60;, &#x60;\&quot;rejected\&quot;&#x60;, &#x60;\&quot;cancelled\&quot;&#x60;, &#x60;\&quot;untriggered\&quot;&#x60; or &#x60;\&quot;archive\&quot;&#x60; (if order was archived)

  # uncomment below to test the property 
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

test_that("label", {
  # tests for the property `label` (character)
  # User defined label (presented only when previously set for order by user)

  # uncomment below to test the property 
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("index_price", {
  # tests for the property `index_price` (numeric)
  # Index Price at the moment of trade

  # uncomment below to test the property 
  #expect_equal(model.instance$`index_price`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (numeric)
  # Trade amount. For perpetual and futures - in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH.

  # uncomment below to test the property 
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("instrument_name", {
  # tests for the property `instrument_name` (character)
  # Unique instrument identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`instrument_name`, "EXPECTED_RESULT")
})

test_that("tick_direction", {
  # tests for the property `tick_direction` (integer)
  # Direction of the \&quot;tick\&quot; (&#x60;0&#x60; &#x3D; Plus Tick, &#x60;1&#x60; &#x3D; Zero-Plus Tick, &#x60;2&#x60; &#x3D; Minus Tick, &#x60;3&#x60; &#x3D; Zero-Minus Tick).

  # uncomment below to test the property 
  #expect_equal(model.instance$`tick_direction`, "EXPECTED_RESULT")
})

test_that("matching_id", {
  # tests for the property `matching_id` (character)
  # Always &#x60;null&#x60;, except for a self-trade which is possible only if self-trading is switched on for the account (in that case this will be id of the maker order of the subscriber)

  # uncomment below to test the property 
  #expect_equal(model.instance$`matching_id`, "EXPECTED_RESULT")
})

test_that("liquidity", {
  # tests for the property `liquidity` (character)
  # Describes what was role of users order: &#x60;\&quot;M\&quot;&#x60; when it was maker order, &#x60;\&quot;T\&quot;&#x60; when it was taker order

  # uncomment below to test the property 
  #expect_equal(model.instance$`liquidity`, "EXPECTED_RESULT")
})

