# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WebsocketOnlyApi")

api.instance <- WebsocketOnlyApi$new()

test_that("PrivateDisableCancelOnDisconnectGet", {
  # tests for PrivateDisableCancelOnDisconnectGet
  # base path: https://www.deribit.com/api/v2
  # Disable Cancel On Disconnect for the connection. This does not change the default account setting.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateEnableCancelOnDisconnectGet", {
  # tests for PrivateEnableCancelOnDisconnectGet
  # base path: https://www.deribit.com/api/v2
  # Enable Cancel On Disconnect for the connection. This does not change the default account setting.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateLogoutGet", {
  # tests for PrivateLogoutGet
  # base path: https://www.deribit.com/api/v2
  # Gracefully close websocket connection, when COD (Cancel On Disconnect) is enabled orders are not cancelled
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSubscribeGet", {
  # tests for PrivateSubscribeGet
  # base path: https://www.deribit.com/api/v2
  # Subscribe to one or more channels.
  # Subscribe to one or more channels.  The name of the channel determines what information will be provided, and in what form. 
  # @param character  channels  A list of channels to subscribe to. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateUnsubscribeGet", {
  # tests for PrivateUnsubscribeGet
  # base path: https://www.deribit.com/api/v2
  # Unsubscribe from one or more channels.
  # @param character  channels  A list of channels to unsubscribe from. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicDisableHeartbeatGet", {
  # tests for PublicDisableHeartbeatGet
  # base path: https://www.deribit.com/api/v2
  # Stop sending heartbeat messages.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicHelloGet", {
  # tests for PublicHelloGet
  # base path: https://www.deribit.com/api/v2
  # Method used to introduce the client software connected to Deribit platform over websocket. Provided data may have an impact on the maintained connection and will be collected for internal statistical purposes. In response, Deribit will also introduce itself.
  # @param character  client.name  Client software name 
  # @param character  client.version  Client software version 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicSetHeartbeatGet", {
  # tests for PublicSetHeartbeatGet
  # base path: https://www.deribit.com/api/v2
  # Signals the Websocket connection to send and request heartbeats. Heartbeats can be used to detect stale connections. When heartbeats have been set up, the API server will send &#x60;heartbeat&#x60; messages and &#x60;test_request&#x60; messages. Your software should respond to &#x60;test_request&#x60; messages by sending a &#x60;/api/v2/public/test&#x60; request. If your software fails to do so, the API server will immediately close the connection. If your account is configured to cancel on disconnect, any orders opened over the connection will be cancelled.
  # @param numeric  interval  The heartbeat interval in seconds, but not less than 10 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicSubscribeGet", {
  # tests for PublicSubscribeGet
  # base path: https://www.deribit.com/api/v2
  # Subscribe to one or more channels.
  # Subscribe to one or more channels.  This is the same method as [/private/subscribe](#private_subscribe), but it can only be used for &#39;public&#39; channels. 
  # @param character  channels  A list of channels to subscribe to. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicUnsubscribeGet", {
  # tests for PublicUnsubscribeGet
  # base path: https://www.deribit.com/api/v2
  # Unsubscribe from one or more channels.
  # @param character  channels  A list of channels to unsubscribe from. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

