# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PublicTrade")

model.instance <- PublicTrade$new()

test_that("direction", {
  # tests for the property `direction` (character)
  # Trade direction of the taker

  # uncomment below to test the property 
  #expect_equal(model.instance$`direction`, "EXPECTED_RESULT")
})

test_that("tick_direction", {
  # tests for the property `tick_direction` (integer)
  # Direction of the \&quot;tick\&quot; (&#x60;0&#x60; &#x3D; Plus Tick, &#x60;1&#x60; &#x3D; Zero-Plus Tick, &#x60;2&#x60; &#x3D; Minus Tick, &#x60;3&#x60; &#x3D; Zero-Minus Tick).

  # uncomment below to test the property 
  #expect_equal(model.instance$`tick_direction`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (integer)
  # The timestamp of the trade

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("price", {
  # tests for the property `price` (numeric)
  # The price of the trade

  # uncomment below to test the property 
  #expect_equal(model.instance$`price`, "EXPECTED_RESULT")
})

test_that("trade_seq", {
  # tests for the property `trade_seq` (integer)
  # The sequence number of the trade within instrument

  # uncomment below to test the property 
  #expect_equal(model.instance$`trade_seq`, "EXPECTED_RESULT")
})

test_that("trade_id", {
  # tests for the property `trade_id` (character)
  # Unique (per currency) trade identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`trade_id`, "EXPECTED_RESULT")
})

test_that("iv", {
  # tests for the property `iv` (numeric)
  # Option implied volatility for the price (Option only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`iv`, "EXPECTED_RESULT")
})

test_that("index_price", {
  # tests for the property `index_price` (numeric)
  # Index Price at the moment of trade

  # uncomment below to test the property 
  #expect_equal(model.instance$`index_price`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (numeric)
  # Trade amount. For perpetual and futures - in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH.

  # uncomment below to test the property 
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("instrument_name", {
  # tests for the property `instrument_name` (character)
  # Unique instrument identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`instrument_name`, "EXPECTED_RESULT")
})

