# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InternalApi")

api.instance <- InternalApi$new()

test_that("PrivateAddToAddressBookGet", {
  # tests for PrivateAddToAddressBookGet
  # base path: https://www.deribit.com/api/v2
  # Adds new entry to address book of given type
  # @param character  currency  The currency symbol 
  # @param character  type  Address book type 
  # @param character  address  Address in currency format, it must be in address book 
  # @param character  name  Name of address book entry 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateDisableTfaWithRecoveryCodeGet", {
  # tests for PrivateDisableTfaWithRecoveryCodeGet
  # base path: https://www.deribit.com/api/v2
  # Disables TFA with one time recovery code
  # @param character  password  The password for the subaccount 
  # @param character  code  One time recovery code 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetAddressBookGet", {
  # tests for PrivateGetAddressBookGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves address book of given type
  # @param character  currency  The currency symbol 
  # @param character  type  Address book type 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateRemoveFromAddressBookGet", {
  # tests for PrivateRemoveFromAddressBookGet
  # base path: https://www.deribit.com/api/v2
  # Adds new entry to address book of given type
  # @param character  currency  The currency symbol 
  # @param character  type  Address book type 
  # @param character  address  Address in currency format, it must be in address book 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSubmitTransferToSubaccountGet", {
  # tests for PrivateSubmitTransferToSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Transfer funds to a subaccount.
  # @param character  currency  The currency symbol 
  # @param numeric  amount  Amount of funds to be transferred 
  # @param integer  destination  Id of destination subaccount 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSubmitTransferToUserGet", {
  # tests for PrivateSubmitTransferToUserGet
  # base path: https://www.deribit.com/api/v2
  # Transfer funds to a another user.
  # @param character  currency  The currency symbol 
  # @param numeric  amount  Amount of funds to be transferred 
  # @param character  destination  Destination address from address book 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateToggleDepositAddressCreationGet", {
  # tests for PrivateToggleDepositAddressCreationGet
  # base path: https://www.deribit.com/api/v2
  # Enable or disable deposit address creation
  # @param character  currency  The currency symbol 
  # @param character  state   
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetFooterGet", {
  # tests for PublicGetFooterGet
  # base path: https://www.deribit.com/api/v2
  # Get information to be displayed in the footer of the website.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetOptionMarkPricesGet", {
  # tests for PublicGetOptionMarkPricesGet
  # base path: https://www.deribit.com/api/v2
  # Retrives market prices and its implied volatility of options instruments
  # @param character  currency  The currency symbol 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicValidateFieldGet", {
  # tests for PublicValidateFieldGet
  # base path: https://www.deribit.com/api/v2
  # Method used to introduce the client software connected to Deribit platform over websocket. Provided data may have an impact on the maintained connection and will be collected for internal statistical purposes. In response, Deribit will also introduce itself.
  # @param character  field  Name of the field to be validated, examples: postal_code, date_of_birth 
  # @param character  value  Value to be checked 
  # @param character  value2  Additional value to be compared with  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

