# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BookSummary")

model.instance <- BookSummary$new()

test_that("underlying_index", {
  # tests for the property `underlying_index` (character)
  # Name of the underlying future, or &#x60;&#39;index_price&#39;&#x60; (options only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`underlying_index`, "EXPECTED_RESULT")
})

test_that("volume", {
  # tests for the property `volume` (numeric)
  # The total 24h traded volume (in base currency)

  # uncomment below to test the property 
  #expect_equal(model.instance$`volume`, "EXPECTED_RESULT")
})

test_that("volume_usd", {
  # tests for the property `volume_usd` (numeric)
  # Volume in usd (futures only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`volume_usd`, "EXPECTED_RESULT")
})

test_that("underlying_price", {
  # tests for the property `underlying_price` (numeric)
  # underlying price for implied volatility calculations (options only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`underlying_price`, "EXPECTED_RESULT")
})

test_that("bid_price", {
  # tests for the property `bid_price` (numeric)
  # The current best bid price, &#x60;null&#x60; if there aren&#39;t any bids

  # uncomment below to test the property 
  #expect_equal(model.instance$`bid_price`, "EXPECTED_RESULT")
})

test_that("open_interest", {
  # tests for the property `open_interest` (numeric)
  # The total amount of outstanding contracts in the corresponding amount units. For perpetual and futures the amount is in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH.

  # uncomment below to test the property 
  #expect_equal(model.instance$`open_interest`, "EXPECTED_RESULT")
})

test_that("quote_currency", {
  # tests for the property `quote_currency` (character)
  # Quote currency

  # uncomment below to test the property 
  #expect_equal(model.instance$`quote_currency`, "EXPECTED_RESULT")
})

test_that("high", {
  # tests for the property `high` (numeric)
  # Price of the 24h highest trade

  # uncomment below to test the property 
  #expect_equal(model.instance$`high`, "EXPECTED_RESULT")
})

test_that("estimated_delivery_price", {
  # tests for the property `estimated_delivery_price` (numeric)
  # Estimated delivery price, in USD (futures only). For more details, see Documentation &gt; General &gt; Expiration Price

  # uncomment below to test the property 
  #expect_equal(model.instance$`estimated_delivery_price`, "EXPECTED_RESULT")
})

test_that("last", {
  # tests for the property `last` (numeric)
  # The price of the latest trade, &#x60;null&#x60; if there weren&#39;t any trades

  # uncomment below to test the property 
  #expect_equal(model.instance$`last`, "EXPECTED_RESULT")
})

test_that("mid_price", {
  # tests for the property `mid_price` (numeric)
  # The average of the best bid and ask, &#x60;null&#x60; if there aren&#39;t any asks or bids

  # uncomment below to test the property 
  #expect_equal(model.instance$`mid_price`, "EXPECTED_RESULT")
})

test_that("interest_rate", {
  # tests for the property `interest_rate` (numeric)
  # Interest rate used in implied volatility calculations (options only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`interest_rate`, "EXPECTED_RESULT")
})

test_that("funding_8h", {
  # tests for the property `funding_8h` (numeric)
  # Funding 8h (perpetual only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`funding_8h`, "EXPECTED_RESULT")
})

test_that("mark_price", {
  # tests for the property `mark_price` (numeric)
  # The current instrument market price

  # uncomment below to test the property 
  #expect_equal(model.instance$`mark_price`, "EXPECTED_RESULT")
})

test_that("ask_price", {
  # tests for the property `ask_price` (numeric)
  # The current best ask price, &#x60;null&#x60; if there aren&#39;t any asks

  # uncomment below to test the property 
  #expect_equal(model.instance$`ask_price`, "EXPECTED_RESULT")
})

test_that("instrument_name", {
  # tests for the property `instrument_name` (character)
  # Unique instrument identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`instrument_name`, "EXPECTED_RESULT")
})

test_that("low", {
  # tests for the property `low` (numeric)
  # Price of the 24h lowest trade, &#x60;null&#x60; if there weren&#39;t any trades

  # uncomment below to test the property 
  #expect_equal(model.instance$`low`, "EXPECTED_RESULT")
})

test_that("base_currency", {
  # tests for the property `base_currency` (character)
  # Base currency

  # uncomment below to test the property 
  #expect_equal(model.instance$`base_currency`, "EXPECTED_RESULT")
})

test_that("creation_timestamp", {
  # tests for the property `creation_timestamp` (integer)
  # The timestamp (seconds since the Unix epoch, with millisecond precision)

  # uncomment below to test the property 
  #expect_equal(model.instance$`creation_timestamp`, "EXPECTED_RESULT")
})

test_that("current_funding", {
  # tests for the property `current_funding` (numeric)
  # Current funding (perpetual only)

  # uncomment below to test the property 
  #expect_equal(model.instance$`current_funding`, "EXPECTED_RESULT")
})

