# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuthenticationApi")

api.instance <- AuthenticationApi$new()

test_that("PublicAuthGet", {
  # tests for PublicAuthGet
  # base path: https://www.deribit.com/api/v2
  # Authenticate
  # Retrieve an Oauth access token, to be used for authentication of &#39;private&#39; requests.  Three methods of authentication are supported:  - &lt;code&gt;password&lt;/code&gt; - using email and and password as when logging on to the website - &lt;code&gt;client_credentials&lt;/code&gt; - using the access key and access secret that can be found on the API page on the website - &lt;code&gt;client_signature&lt;/code&gt; - using the access key that can be found on the API page on the website and user generated signature. The signature is calculated using some fields provided in the request, using formula described here [Deribit signature credentials](#additional-authorization-method-deribit-signature-credentials) - &lt;code&gt;refresh_token&lt;/code&gt; - using a refresh token that was received from an earlier invocation  The response will contain an access token, expiration period (number of seconds that the token is valid) and a refresh token that can be used to get a new set of tokens. 
  # @param character  grant.type  Method of authentication 
  # @param character  username  Required for grant type `password` 
  # @param character  password  Required for grant type `password` 
  # @param character  client.id  Required for grant type `client_credentials` and `client_signature` 
  # @param character  client.secret  Required for grant type `client_credentials` 
  # @param character  refresh.token  Required for grant type `refresh_token` 
  # @param character  timestamp  Required for grant type `client_signature`, provides time when request has been generated 
  # @param character  signature  Required for grant type `client_signature`; it's a cryptographic signature calculated over provided fields using user **secret key**. The signature should be calculated as an HMAC (Hash-based Message Authentication Code) with `SHA256` hash algorithm 
  # @param character  nonce  Optional for grant type `client_signature`; delivers user generated initialization vector for the server token  (optional)
  # @param character  state  Will be passed back in the response  (optional)
  # @param character  scope  Describes type of the access for assigned token, possible values: `connection`, `session`, `session:name`, `trade:[read, read_write, none]`, `wallet:[read, read_write, none]`, `account:[read, read_write, none]`, `expires:NUMBER` (token will expire after `NUMBER` of seconds).</BR></BR> **NOTICE:** Depending on choosing an authentication method (```grant type```) some scopes could be narrowed by the server. e.g. when ```grant_type = client_credentials``` and ```scope = wallet:read_write``` it's modified by the server as ```scope = wallet:read```  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

