# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AddressBookItem")

model.instance <- AddressBookItem$new()

test_that("currency", {
  # tests for the property `currency` (character)
  # Currency, i.e &#x60;\&quot;BTC\&quot;&#x60;, &#x60;\&quot;ETH\&quot;&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency`, "EXPECTED_RESULT")
})

test_that("address", {
  # tests for the property `address` (character)
  # Address in proper format for currency

  # uncomment below to test the property 
  #expect_equal(model.instance$`address`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # Address book type

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("creation_timestamp", {
  # tests for the property `creation_timestamp` (integer)
  # The timestamp (seconds since the Unix epoch, with millisecond precision)

  # uncomment below to test the property 
  #expect_equal(model.instance$`creation_timestamp`, "EXPECTED_RESULT")
})

