# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SessionManagementApi")

api.instance <- SessionManagementApi$new()

test_that("PrivateDisableCancelOnDisconnectGet", {
  # tests for PrivateDisableCancelOnDisconnectGet
  # base path: https://www.deribit.com/api/v2
  # Disable Cancel On Disconnect for the connection. This does not change the default account setting.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateEnableCancelOnDisconnectGet", {
  # tests for PrivateEnableCancelOnDisconnectGet
  # base path: https://www.deribit.com/api/v2
  # Enable Cancel On Disconnect for the connection. This does not change the default account setting.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicDisableHeartbeatGet", {
  # tests for PublicDisableHeartbeatGet
  # base path: https://www.deribit.com/api/v2
  # Stop sending heartbeat messages.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicSetHeartbeatGet", {
  # tests for PublicSetHeartbeatGet
  # base path: https://www.deribit.com/api/v2
  # Signals the Websocket connection to send and request heartbeats. Heartbeats can be used to detect stale connections. When heartbeats have been set up, the API server will send &#x60;heartbeat&#x60; messages and &#x60;test_request&#x60; messages. Your software should respond to &#x60;test_request&#x60; messages by sending a &#x60;/api/v2/public/test&#x60; request. If your software fails to do so, the API server will immediately close the connection. If your account is configured to cancel on disconnect, any orders opened over the connection will be cancelled.
  # @param numeric  interval  The heartbeat interval in seconds, but not less than 10 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

