# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TradesVolumes")

model.instance <- TradesVolumes$new()

test_that("calls_volume", {
  # tests for the property `calls_volume` (numeric)
  # Total 24h trade volume for call options. This is expressed in the base currency, e.g. BTC for &#x60;btc_usd&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`calls_volume`, "EXPECTED_RESULT")
})

test_that("puts_volume", {
  # tests for the property `puts_volume` (numeric)
  # Total 24h trade volume for put options. This is expressed in the base currency, e.g. BTC for &#x60;btc_usd&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`puts_volume`, "EXPECTED_RESULT")
})

test_that("currency_pair", {
  # tests for the property `currency_pair` (character)
  # Currency pair: &#x60;\&quot;btc_usd\&quot;&#x60; or &#x60;\&quot;eth_usd\&quot;&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency_pair`, "EXPECTED_RESULT")
})

test_that("futures_volume", {
  # tests for the property `futures_volume` (numeric)
  # Total 24h trade volume for futures. This is expressed in the base currency, e.g. BTC for &#x60;btc_usd&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`futures_volume`, "EXPECTED_RESULT")
})

