# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Order")

model.instance <- Order$new()

test_that("direction", {
  # tests for the property `direction` (character)
  # direction, &#x60;buy&#x60; or &#x60;sell&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`direction`, "EXPECTED_RESULT")
})

test_that("reduce_only", {
  # tests for the property `reduce_only` (character)
  # &#x60;true&#x60; for reduce-only orders only

  # uncomment below to test the property 
  #expect_equal(model.instance$`reduce_only`, "EXPECTED_RESULT")
})

test_that("triggered", {
  # tests for the property `triggered` (character)
  # Whether the stop order has been triggered (Only for stop orders)

  # uncomment below to test the property 
  #expect_equal(model.instance$`triggered`, "EXPECTED_RESULT")
})

test_that("order_id", {
  # tests for the property `order_id` (character)
  # Unique order identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`order_id`, "EXPECTED_RESULT")
})

test_that("price", {
  # tests for the property `price` (numeric)
  # Price in base currency

  # uncomment below to test the property 
  #expect_equal(model.instance$`price`, "EXPECTED_RESULT")
})

test_that("time_in_force", {
  # tests for the property `time_in_force` (character)
  # Order time in force: &#x60;\&quot;good_til_cancelled\&quot;&#x60;, &#x60;\&quot;fill_or_kill\&quot;&#x60;, &#x60;\&quot;immediate_or_cancel\&quot;&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`time_in_force`, "EXPECTED_RESULT")
})

test_that("api", {
  # tests for the property `api` (character)
  # &#x60;true&#x60; if created with API

  # uncomment below to test the property 
  #expect_equal(model.instance$`api`, "EXPECTED_RESULT")
})

test_that("order_state", {
  # tests for the property `order_state` (character)
  # order state, &#x60;\&quot;open\&quot;&#x60;, &#x60;\&quot;filled\&quot;&#x60;, &#x60;\&quot;rejected\&quot;&#x60;, &#x60;\&quot;cancelled\&quot;&#x60;, &#x60;\&quot;untriggered\&quot;&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`order_state`, "EXPECTED_RESULT")
})

test_that("implv", {
  # tests for the property `implv` (numeric)
  # Implied volatility in percent. (Only if &#x60;advanced&#x3D;\&quot;implv\&quot;&#x60;)

  # uncomment below to test the property 
  #expect_equal(model.instance$`implv`, "EXPECTED_RESULT")
})

test_that("advanced", {
  # tests for the property `advanced` (character)
  # advanced type: &#x60;\&quot;usd\&quot;&#x60; or &#x60;\&quot;implv\&quot;&#x60; (Only for options; field is omitted if not applicable). 

  # uncomment below to test the property 
  #expect_equal(model.instance$`advanced`, "EXPECTED_RESULT")
})

test_that("post_only", {
  # tests for the property `post_only` (character)
  # &#x60;true&#x60; for post-only orders only

  # uncomment below to test the property 
  #expect_equal(model.instance$`post_only`, "EXPECTED_RESULT")
})

test_that("usd", {
  # tests for the property `usd` (numeric)
  # Option price in USD (Only if &#x60;advanced&#x3D;\&quot;usd\&quot;&#x60;)

  # uncomment below to test the property 
  #expect_equal(model.instance$`usd`, "EXPECTED_RESULT")
})

test_that("stop_price", {
  # tests for the property `stop_price` (numeric)
  # stop price (Only for future stop orders)

  # uncomment below to test the property 
  #expect_equal(model.instance$`stop_price`, "EXPECTED_RESULT")
})

test_that("order_type", {
  # tests for the property `order_type` (character)
  # order type, &#x60;\&quot;limit\&quot;&#x60;, &#x60;\&quot;market\&quot;&#x60;, &#x60;\&quot;stop_limit\&quot;&#x60;, &#x60;\&quot;stop_market\&quot;&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`order_type`, "EXPECTED_RESULT")
})

test_that("last_update_timestamp", {
  # tests for the property `last_update_timestamp` (integer)
  # The timestamp (seconds since the Unix epoch, with millisecond precision)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_update_timestamp`, "EXPECTED_RESULT")
})

test_that("original_order_type", {
  # tests for the property `original_order_type` (character)
  # Original order type. Optional field

  # uncomment below to test the property 
  #expect_equal(model.instance$`original_order_type`, "EXPECTED_RESULT")
})

test_that("max_show", {
  # tests for the property `max_show` (numeric)
  # Maximum amount within an order to be shown to other traders, 0 for invisible order.

  # uncomment below to test the property 
  #expect_equal(model.instance$`max_show`, "EXPECTED_RESULT")
})

test_that("profit_loss", {
  # tests for the property `profit_loss` (numeric)
  # Profit and loss in base currency.

  # uncomment below to test the property 
  #expect_equal(model.instance$`profit_loss`, "EXPECTED_RESULT")
})

test_that("is_liquidation", {
  # tests for the property `is_liquidation` (character)
  # &#x60;true&#x60; if order was automatically created during liquidation

  # uncomment below to test the property 
  #expect_equal(model.instance$`is_liquidation`, "EXPECTED_RESULT")
})

test_that("filled_amount", {
  # tests for the property `filled_amount` (numeric)
  # Filled amount of the order. For perpetual and futures the filled_amount is in USD units, for options - in units or corresponding cryptocurrency contracts, e.g., BTC or ETH.

  # uncomment below to test the property 
  #expect_equal(model.instance$`filled_amount`, "EXPECTED_RESULT")
})

test_that("label", {
  # tests for the property `label` (character)
  # user defined label (up to 32 characters)

  # uncomment below to test the property 
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("commission", {
  # tests for the property `commission` (numeric)
  # Commission paid so far (in base currency)

  # uncomment below to test the property 
  #expect_equal(model.instance$`commission`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (numeric)
  # It represents the requested order size. For perpetual and futures the amount is in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH.

  # uncomment below to test the property 
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("trigger", {
  # tests for the property `trigger` (character)
  # Trigger type (Only for stop orders). Allowed values: &#x60;\&quot;index_price\&quot;&#x60;, &#x60;\&quot;mark_price\&quot;&#x60;, &#x60;\&quot;last_price\&quot;&#x60;.

  # uncomment below to test the property 
  #expect_equal(model.instance$`trigger`, "EXPECTED_RESULT")
})

test_that("instrument_name", {
  # tests for the property `instrument_name` (character)
  # Unique instrument identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`instrument_name`, "EXPECTED_RESULT")
})

test_that("creation_timestamp", {
  # tests for the property `creation_timestamp` (integer)
  # The timestamp (seconds since the Unix epoch, with millisecond precision)

  # uncomment below to test the property 
  #expect_equal(model.instance$`creation_timestamp`, "EXPECTED_RESULT")
})

test_that("average_price", {
  # tests for the property `average_price` (numeric)
  # Average fill price of the order

  # uncomment below to test the property 
  #expect_equal(model.instance$`average_price`, "EXPECTED_RESULT")
})

