# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AccountManagementApi")

api.instance <- AccountManagementApi$new()

test_that("PrivateChangeSubaccountNameGet", {
  # tests for PrivateChangeSubaccountNameGet
  # base path: https://www.deribit.com/api/v2
  # Change the user name for a subaccount
  # @param integer  sid  The user id for the subaccount 
  # @param character  name  The new user name 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCreateSubaccountGet", {
  # tests for PrivateCreateSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Create a new subaccount
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateDisableTfaForSubaccountGet", {
  # tests for PrivateDisableTfaForSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Disable two factor authentication for a subaccount.
  # @param integer  sid  The user id for the subaccount 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetAccountSummaryGet", {
  # tests for PrivateGetAccountSummaryGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves user account summary.
  # @param character  currency  The currency symbol 
  # @param character  extended  Include additional fields  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetEmailLanguageGet", {
  # tests for PrivateGetEmailLanguageGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves the language to be used for emails.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetNewAnnouncementsGet", {
  # tests for PrivateGetNewAnnouncementsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves announcements that have not been marked read by the user.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetPositionGet", {
  # tests for PrivateGetPositionGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve user position.
  # @param character  instrument.name  Instrument name 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetPositionsGet", {
  # tests for PrivateGetPositionsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve user positions.
  # @param character  currency   
  # @param character  kind  Kind filter on positions  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetSubaccountsGet", {
  # tests for PrivateGetSubaccountsGet
  # base path: https://www.deribit.com/api/v2
  # Get information about subaccounts
  # @param character  with.portfolio    (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSetAnnouncementAsReadGet", {
  # tests for PrivateSetAnnouncementAsReadGet
  # base path: https://www.deribit.com/api/v2
  # Marks an announcement as read, so it will not be shown in &#x60;get_new_announcements&#x60;.
  # @param numeric  announcement.id  the ID of the announcement 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSetEmailForSubaccountGet", {
  # tests for PrivateSetEmailForSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Assign an email address to a subaccount. User will receive an email with confirmation link.
  # @param integer  sid  The user id for the subaccount 
  # @param character  email  The email address for the subaccount 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSetEmailLanguageGet", {
  # tests for PrivateSetEmailLanguageGet
  # base path: https://www.deribit.com/api/v2
  # Changes the language to be used for emails.
  # @param character  language  The abbreviated language name. Valid values include `\"en\"`, `\"ko\"`, `\"zh\"` 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSetPasswordForSubaccountGet", {
  # tests for PrivateSetPasswordForSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Set the password for the subaccount
  # @param integer  sid  The user id for the subaccount 
  # @param character  password  The password for the subaccount 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateToggleNotificationsFromSubaccountGet", {
  # tests for PrivateToggleNotificationsFromSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Enable or disable sending of notifications for the subaccount.
  # @param integer  sid  The user id for the subaccount 
  # @param character  state  enable (`true`) or disable (`false`) notifications 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateToggleSubaccountLoginGet", {
  # tests for PrivateToggleSubaccountLoginGet
  # base path: https://www.deribit.com/api/v2
  # Enable or disable login for a subaccount. If login is disabled and a session for the subaccount exists, this session will be terminated.
  # @param integer  sid  The user id for the subaccount 
  # @param character  state  enable or disable login. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetAnnouncementsGet", {
  # tests for PublicGetAnnouncementsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves announcements from the last 30 days.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

