# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Deposit")

model.instance <- Deposit$new()

test_that("updated_timestamp", {
  # tests for the property `updated_timestamp` (integer)
  # The timestamp (seconds since the Unix epoch, with millisecond precision)

  # uncomment below to test the property 
  #expect_equal(model.instance$`updated_timestamp`, "EXPECTED_RESULT")
})

test_that("state", {
  # tests for the property `state` (character)
  # Deposit state, allowed values : &#x60;pending&#x60;, &#x60;completed&#x60;, &#x60;rejected&#x60;, &#x60;replaced&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

test_that("received_timestamp", {
  # tests for the property `received_timestamp` (integer)
  # The timestamp (seconds since the Unix epoch, with millisecond precision)

  # uncomment below to test the property 
  #expect_equal(model.instance$`received_timestamp`, "EXPECTED_RESULT")
})

test_that("currency", {
  # tests for the property `currency` (character)
  # Currency, i.e &#x60;\&quot;BTC\&quot;&#x60;, &#x60;\&quot;ETH\&quot;&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency`, "EXPECTED_RESULT")
})

test_that("address", {
  # tests for the property `address` (character)
  # Address in proper format for currency

  # uncomment below to test the property 
  #expect_equal(model.instance$`address`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (numeric)
  # Amount of funds in given currency

  # uncomment below to test the property 
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("transaction_id", {
  # tests for the property `transaction_id` (character)
  # Transaction id in proper format for currency, &#x60;null&#x60; if id is not available

  # uncomment below to test the property 
  #expect_equal(model.instance$`transaction_id`, "EXPECTED_RESULT")
})

