# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PrivateApi")

api.instance <- PrivateApi$new()

test_that("PrivateAddToAddressBookGet", {
  # tests for PrivateAddToAddressBookGet
  # base path: https://www.deribit.com/api/v2
  # Adds new entry to address book of given type
  # @param character  currency  The currency symbol 
  # @param character  type  Address book type 
  # @param character  address  Address in currency format, it must be in address book 
  # @param character  name  Name of address book entry 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateBuyGet", {
  # tests for PrivateBuyGet
  # base path: https://www.deribit.com/api/v2
  # Places a buy order for an instrument.
  # @param character  instrument.name  Instrument name 
  # @param numeric  amount  It represents the requested order size. For perpetual and futures the amount is in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH 
  # @param character  type  The order type, default: `\"limit\"`  (optional)
  # @param character  label  user defined label for the order (maximum 32 characters)  (optional)
  # @param numeric  price  <p>The order price in base currency (Only for limit and stop_limit orders)</p> <p>When adding order with advanced=usd, the field price should be the option price value in USD.</p> <p>When adding order with advanced=implv, the field price should be a value of implied volatility in percentages. For example,  price=100, means implied volatility of 100%</p>  (optional)
  # @param character  time.in.force  <p>Specifies how long the order remains in effect. Default `\"good_til_cancelled\"`</p> <ul> <li>`\"good_til_cancelled\"` - unfilled order remains in order book until cancelled</li> <li>`\"fill_or_kill\"` - execute a transaction immediately and completely or not at all</li> <li>`\"immediate_or_cancel\"` - execute a transaction immediately, and any portion of the order that cannot be immediately filled is cancelled</li> </ul>  (optional)
  # @param numeric  max.show  Maximum amount within an order to be shown to other customers, `0` for invisible order  (optional)
  # @param character  post.only  <p>If true, the order is considered post-only. If the new price would cause the order to be filled immediately (as taker), the price will be changed to be just below the bid.</p> <p>Only valid in combination with time_in_force=`\"good_til_cancelled\"`</p>  (optional)
  # @param character  reduce.only  If `true`, the order is considered reduce-only which is intended to only reduce a current position  (optional)
  # @param numeric  stop.price  Stop price, required for stop limit orders (Only for stop orders)  (optional)
  # @param character  trigger  Defines trigger type, required for `\"stop_limit\"` order type  (optional)
  # @param character  advanced  Advanced option order type. (Only for options)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCancelAllByCurrencyGet", {
  # tests for PrivateCancelAllByCurrencyGet
  # base path: https://www.deribit.com/api/v2
  # Cancels all orders by currency, optionally filtered by instrument kind and/or order type.
  # @param character  currency  The currency symbol 
  # @param character  kind  Instrument kind, if not provided instruments of all kinds are considered  (optional)
  # @param character  type  Order type - limit, stop or all, default - `all`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCancelAllByInstrumentGet", {
  # tests for PrivateCancelAllByInstrumentGet
  # base path: https://www.deribit.com/api/v2
  # Cancels all orders by instrument, optionally filtered by order type.
  # @param character  instrument.name  Instrument name 
  # @param character  type  Order type - limit, stop or all, default - `all`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCancelAllGet", {
  # tests for PrivateCancelAllGet
  # base path: https://www.deribit.com/api/v2
  # This method cancels all users orders and stop orders within all currencies and instrument kinds.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCancelGet", {
  # tests for PrivateCancelGet
  # base path: https://www.deribit.com/api/v2
  # Cancel an order, specified by order id
  # @param character  order.id  The order id 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCancelTransferByIdGet", {
  # tests for PrivateCancelTransferByIdGet
  # base path: https://www.deribit.com/api/v2
  # Cancel transfer
  # @param character  currency  The currency symbol 
  # @param integer  id  Id of transfer 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCancelWithdrawalGet", {
  # tests for PrivateCancelWithdrawalGet
  # base path: https://www.deribit.com/api/v2
  # Cancels withdrawal request
  # @param character  currency  The currency symbol 
  # @param numeric  id  The withdrawal id 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateChangeSubaccountNameGet", {
  # tests for PrivateChangeSubaccountNameGet
  # base path: https://www.deribit.com/api/v2
  # Change the user name for a subaccount
  # @param integer  sid  The user id for the subaccount 
  # @param character  name  The new user name 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateClosePositionGet", {
  # tests for PrivateClosePositionGet
  # base path: https://www.deribit.com/api/v2
  # Makes closing position reduce only order .
  # @param character  instrument.name  Instrument name 
  # @param character  type  The order type 
  # @param numeric  price  Optional price for limit order.  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCreateDepositAddressGet", {
  # tests for PrivateCreateDepositAddressGet
  # base path: https://www.deribit.com/api/v2
  # Creates deposit address in currency
  # @param character  currency  The currency symbol 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateCreateSubaccountGet", {
  # tests for PrivateCreateSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Create a new subaccount
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateDisableTfaForSubaccountGet", {
  # tests for PrivateDisableTfaForSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Disable two factor authentication for a subaccount.
  # @param integer  sid  The user id for the subaccount 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateDisableTfaWithRecoveryCodeGet", {
  # tests for PrivateDisableTfaWithRecoveryCodeGet
  # base path: https://www.deribit.com/api/v2
  # Disables TFA with one time recovery code
  # @param character  password  The password for the subaccount 
  # @param character  code  One time recovery code 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateEditGet", {
  # tests for PrivateEditGet
  # base path: https://www.deribit.com/api/v2
  # Change price, amount and/or other properties of an order.
  # @param character  order.id  The order id 
  # @param numeric  amount  It represents the requested order size. For perpetual and futures the amount is in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH 
  # @param numeric  price  <p>The order price in base currency.</p> <p>When editing an option order with advanced=usd, the field price should be the option price value in USD.</p> <p>When editing an option order with advanced=implv, the field price should be a value of implied volatility in percentages. For example,  price=100, means implied volatility of 100%</p> 
  # @param character  post.only  <p>If true, the order is considered post-only. If the new price would cause the order to be filled immediately (as taker), the price will be changed to be just below the bid.</p> <p>Only valid in combination with time_in_force=`\"good_til_cancelled\"`</p>  (optional)
  # @param character  advanced  Advanced option order type. If you have posted an advanced option order, it is necessary to re-supply this parameter when editing it (Only for options)  (optional)
  # @param numeric  stop.price  Stop price, required for stop limit orders (Only for stop orders)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetAccountSummaryGet", {
  # tests for PrivateGetAccountSummaryGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves user account summary.
  # @param character  currency  The currency symbol 
  # @param character  extended  Include additional fields  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetAddressBookGet", {
  # tests for PrivateGetAddressBookGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves address book of given type
  # @param character  currency  The currency symbol 
  # @param character  type  Address book type 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetCurrentDepositAddressGet", {
  # tests for PrivateGetCurrentDepositAddressGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve deposit address for currency
  # @param character  currency  The currency symbol 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetDepositsGet", {
  # tests for PrivateGetDepositsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest users deposits
  # @param character  currency  The currency symbol 
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param integer  offset  The offset for pagination, default - `0`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetEmailLanguageGet", {
  # tests for PrivateGetEmailLanguageGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves the language to be used for emails.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetMarginsGet", {
  # tests for PrivateGetMarginsGet
  # base path: https://www.deribit.com/api/v2
  # Get margins for given instrument, amount and price.
  # @param character  instrument.name  Instrument name 
  # @param numeric  amount  Amount, integer for future, float for option. For perpetual and futures the amount is in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH. 
  # @param numeric  price  Price 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetNewAnnouncementsGet", {
  # tests for PrivateGetNewAnnouncementsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves announcements that have not been marked read by the user.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetOpenOrdersByCurrencyGet", {
  # tests for PrivateGetOpenOrdersByCurrencyGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves list of user&#39;s open orders.
  # @param character  currency  The currency symbol 
  # @param character  kind  Instrument kind, if not provided instruments of all kinds are considered  (optional)
  # @param character  type  Order type, default - `all`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetOpenOrdersByInstrumentGet", {
  # tests for PrivateGetOpenOrdersByInstrumentGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves list of user&#39;s open orders within given Instrument.
  # @param character  instrument.name  Instrument name 
  # @param character  type  Order type, default - `all`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetOrderHistoryByCurrencyGet", {
  # tests for PrivateGetOrderHistoryByCurrencyGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves history of orders that have been partially or fully filled.
  # @param character  currency  The currency symbol 
  # @param character  kind  Instrument kind, if not provided instruments of all kinds are considered  (optional)
  # @param integer  count  Number of requested items, default - `20`  (optional)
  # @param integer  offset  The offset for pagination, default - `0`  (optional)
  # @param character  include.old  Include in result orders older than 2 days, default - `false`  (optional)
  # @param character  include.unfilled  Include in result fully unfilled closed orders, default - `false`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetOrderHistoryByInstrumentGet", {
  # tests for PrivateGetOrderHistoryByInstrumentGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves history of orders that have been partially or fully filled.
  # @param character  instrument.name  Instrument name 
  # @param integer  count  Number of requested items, default - `20`  (optional)
  # @param integer  offset  The offset for pagination, default - `0`  (optional)
  # @param character  include.old  Include in result orders older than 2 days, default - `false`  (optional)
  # @param character  include.unfilled  Include in result fully unfilled closed orders, default - `false`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetOrderMarginByIdsGet", {
  # tests for PrivateGetOrderMarginByIdsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves initial margins of given orders
  # @param character  ids  Ids of orders 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetOrderStateGet", {
  # tests for PrivateGetOrderStateGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the current state of an order.
  # @param character  order.id  The order id 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetPositionGet", {
  # tests for PrivateGetPositionGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve user position.
  # @param character  instrument.name  Instrument name 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetPositionsGet", {
  # tests for PrivateGetPositionsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve user positions.
  # @param character  currency   
  # @param character  kind  Kind filter on positions  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetSettlementHistoryByCurrencyGet", {
  # tests for PrivateGetSettlementHistoryByCurrencyGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves settlement, delivery and bankruptcy events that have affected your account.
  # @param character  currency  The currency symbol 
  # @param character  type  Settlement type  (optional)
  # @param integer  count  Number of requested items, default - `20`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetSettlementHistoryByInstrumentGet", {
  # tests for PrivateGetSettlementHistoryByInstrumentGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves public settlement, delivery and bankruptcy events filtered by instrument name
  # @param character  instrument.name  Instrument name 
  # @param character  type  Settlement type  (optional)
  # @param integer  count  Number of requested items, default - `20`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetSubaccountsGet", {
  # tests for PrivateGetSubaccountsGet
  # base path: https://www.deribit.com/api/v2
  # Get information about subaccounts
  # @param character  with.portfolio    (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetTransfersGet", {
  # tests for PrivateGetTransfersGet
  # base path: https://www.deribit.com/api/v2
  # Adds new entry to address book of given type
  # @param character  currency  The currency symbol 
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param integer  offset  The offset for pagination, default - `0`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetUserTradesByCurrencyAndTimeGet", {
  # tests for PrivateGetUserTradesByCurrencyAndTimeGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest user trades that have occurred for instruments in a specific currency symbol and within given time range.
  # @param character  currency  The currency symbol 
  # @param integer  start.timestamp  The earliest timestamp to return result for 
  # @param integer  end.timestamp  The most recent timestamp to return result for 
  # @param character  kind  Instrument kind, if not provided instruments of all kinds are considered  (optional)
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param character  include.old  Include trades older than 7 days, default - `false`  (optional)
  # @param character  sorting  Direction of results sorting (`default` value means no sorting, results will be returned in order in which they left the database)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetUserTradesByCurrencyGet", {
  # tests for PrivateGetUserTradesByCurrencyGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest user trades that have occurred for instruments in a specific currency symbol.
  # @param character  currency  The currency symbol 
  # @param character  kind  Instrument kind, if not provided instruments of all kinds are considered  (optional)
  # @param character  start.id  The ID number of the first trade to be returned  (optional)
  # @param character  end.id  The ID number of the last trade to be returned  (optional)
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param character  include.old  Include trades older than 7 days, default - `false`  (optional)
  # @param character  sorting  Direction of results sorting (`default` value means no sorting, results will be returned in order in which they left the database)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetUserTradesByInstrumentAndTimeGet", {
  # tests for PrivateGetUserTradesByInstrumentAndTimeGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest user trades that have occurred for a specific instrument and within given time range.
  # @param character  instrument.name  Instrument name 
  # @param integer  start.timestamp  The earliest timestamp to return result for 
  # @param integer  end.timestamp  The most recent timestamp to return result for 
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param character  include.old  Include trades older than 7 days, default - `false`  (optional)
  # @param character  sorting  Direction of results sorting (`default` value means no sorting, results will be returned in order in which they left the database)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetUserTradesByInstrumentGet", {
  # tests for PrivateGetUserTradesByInstrumentGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest user trades that have occurred for a specific instrument.
  # @param character  instrument.name  Instrument name 
  # @param integer  start.seq  The sequence number of the first trade to be returned  (optional)
  # @param integer  end.seq  The sequence number of the last trade to be returned  (optional)
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param character  include.old  Include trades older than 7 days, default - `false`  (optional)
  # @param character  sorting  Direction of results sorting (`default` value means no sorting, results will be returned in order in which they left the database)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetUserTradesByOrderGet", {
  # tests for PrivateGetUserTradesByOrderGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the list of user trades that was created for given order
  # @param character  order.id  The order id 
  # @param character  sorting  Direction of results sorting (`default` value means no sorting, results will be returned in order in which they left the database)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateGetWithdrawalsGet", {
  # tests for PrivateGetWithdrawalsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest users withdrawals
  # @param character  currency  The currency symbol 
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param integer  offset  The offset for pagination, default - `0`  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateRemoveFromAddressBookGet", {
  # tests for PrivateRemoveFromAddressBookGet
  # base path: https://www.deribit.com/api/v2
  # Adds new entry to address book of given type
  # @param character  currency  The currency symbol 
  # @param character  type  Address book type 
  # @param character  address  Address in currency format, it must be in address book 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSellGet", {
  # tests for PrivateSellGet
  # base path: https://www.deribit.com/api/v2
  # Places a sell order for an instrument.
  # @param character  instrument.name  Instrument name 
  # @param numeric  amount  It represents the requested order size. For perpetual and futures the amount is in USD units, for options it is amount of corresponding cryptocurrency contracts, e.g., BTC or ETH 
  # @param character  type  The order type, default: `\"limit\"`  (optional)
  # @param character  label  user defined label for the order (maximum 32 characters)  (optional)
  # @param numeric  price  <p>The order price in base currency (Only for limit and stop_limit orders)</p> <p>When adding order with advanced=usd, the field price should be the option price value in USD.</p> <p>When adding order with advanced=implv, the field price should be a value of implied volatility in percentages. For example,  price=100, means implied volatility of 100%</p>  (optional)
  # @param character  time.in.force  <p>Specifies how long the order remains in effect. Default `\"good_til_cancelled\"`</p> <ul> <li>`\"good_til_cancelled\"` - unfilled order remains in order book until cancelled</li> <li>`\"fill_or_kill\"` - execute a transaction immediately and completely or not at all</li> <li>`\"immediate_or_cancel\"` - execute a transaction immediately, and any portion of the order that cannot be immediately filled is cancelled</li> </ul>  (optional)
  # @param numeric  max.show  Maximum amount within an order to be shown to other customers, `0` for invisible order  (optional)
  # @param character  post.only  <p>If true, the order is considered post-only. If the new price would cause the order to be filled immediately (as taker), the price will be changed to be just below the bid.</p> <p>Only valid in combination with time_in_force=`\"good_til_cancelled\"`</p>  (optional)
  # @param character  reduce.only  If `true`, the order is considered reduce-only which is intended to only reduce a current position  (optional)
  # @param numeric  stop.price  Stop price, required for stop limit orders (Only for stop orders)  (optional)
  # @param character  trigger  Defines trigger type, required for `\"stop_limit\"` order type  (optional)
  # @param character  advanced  Advanced option order type. (Only for options)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSetAnnouncementAsReadGet", {
  # tests for PrivateSetAnnouncementAsReadGet
  # base path: https://www.deribit.com/api/v2
  # Marks an announcement as read, so it will not be shown in &#x60;get_new_announcements&#x60;.
  # @param numeric  announcement.id  the ID of the announcement 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSetEmailForSubaccountGet", {
  # tests for PrivateSetEmailForSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Assign an email address to a subaccount. User will receive an email with confirmation link.
  # @param integer  sid  The user id for the subaccount 
  # @param character  email  The email address for the subaccount 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSetEmailLanguageGet", {
  # tests for PrivateSetEmailLanguageGet
  # base path: https://www.deribit.com/api/v2
  # Changes the language to be used for emails.
  # @param character  language  The abbreviated language name. Valid values include `\"en\"`, `\"ko\"`, `\"zh\"` 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSetPasswordForSubaccountGet", {
  # tests for PrivateSetPasswordForSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Set the password for the subaccount
  # @param integer  sid  The user id for the subaccount 
  # @param character  password  The password for the subaccount 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSubmitTransferToSubaccountGet", {
  # tests for PrivateSubmitTransferToSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Transfer funds to a subaccount.
  # @param character  currency  The currency symbol 
  # @param numeric  amount  Amount of funds to be transferred 
  # @param integer  destination  Id of destination subaccount 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateSubmitTransferToUserGet", {
  # tests for PrivateSubmitTransferToUserGet
  # base path: https://www.deribit.com/api/v2
  # Transfer funds to a another user.
  # @param character  currency  The currency symbol 
  # @param numeric  amount  Amount of funds to be transferred 
  # @param character  destination  Destination address from address book 
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateToggleDepositAddressCreationGet", {
  # tests for PrivateToggleDepositAddressCreationGet
  # base path: https://www.deribit.com/api/v2
  # Enable or disable deposit address creation
  # @param character  currency  The currency symbol 
  # @param character  state   
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateToggleNotificationsFromSubaccountGet", {
  # tests for PrivateToggleNotificationsFromSubaccountGet
  # base path: https://www.deribit.com/api/v2
  # Enable or disable sending of notifications for the subaccount.
  # @param integer  sid  The user id for the subaccount 
  # @param character  state  enable (`true`) or disable (`false`) notifications 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateToggleSubaccountLoginGet", {
  # tests for PrivateToggleSubaccountLoginGet
  # base path: https://www.deribit.com/api/v2
  # Enable or disable login for a subaccount. If login is disabled and a session for the subaccount exists, this session will be terminated.
  # @param integer  sid  The user id for the subaccount 
  # @param character  state  enable or disable login. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PrivateWithdrawGet", {
  # tests for PrivateWithdrawGet
  # base path: https://www.deribit.com/api/v2
  # Creates a new withdrawal request
  # @param character  currency  The currency symbol 
  # @param character  address  Address in currency format, it must be in address book 
  # @param numeric  amount  Amount of funds to be withdrawn 
  # @param character  priority  Withdrawal priority, optional for BTC, default: `high`  (optional)
  # @param character  tfa  TFA code, required when TFA is enabled for current account  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

