# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MarketDataApi")

api.instance <- MarketDataApi$new()

test_that("PublicGetBookSummaryByCurrencyGet", {
  # tests for PublicGetBookSummaryByCurrencyGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves the summary information such as open interest, 24h volume, etc. for all instruments for the currency (optionally filtered by kind).
  # @param character  currency  The currency symbol 
  # @param character  kind  Instrument kind, if not provided instruments of all kinds are considered  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetBookSummaryByInstrumentGet", {
  # tests for PublicGetBookSummaryByInstrumentGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves the summary information such as open interest, 24h volume, etc. for a specific instrument.
  # @param character  instrument.name  Instrument name 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetContractSizeGet", {
  # tests for PublicGetContractSizeGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves contract size of provided instrument.
  # @param character  instrument.name  Instrument name 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetCurrenciesGet", {
  # tests for PublicGetCurrenciesGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves all cryptocurrencies supported by the API.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetFundingChartDataGet", {
  # tests for PublicGetFundingChartDataGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest user trades that have occurred for PERPETUAL instruments in a specific currency symbol and within given time range.
  # @param character  instrument.name  Instrument name 
  # @param character  length  Specifies time period. `8h` - 8 hours, `24h` - 24 hours  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetHistoricalVolatilityGet", {
  # tests for PublicGetHistoricalVolatilityGet
  # base path: https://www.deribit.com/api/v2
  # Provides information about historical volatility for given cryptocurrency.
  # @param character  currency  The currency symbol 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetIndexGet", {
  # tests for PublicGetIndexGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves the current index price for the instruments, for the selected currency.
  # @param character  currency  The currency symbol 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetInstrumentsGet", {
  # tests for PublicGetInstrumentsGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves available trading instruments. This method can be used to see which instruments are available for trading, or which instruments have existed historically.
  # @param character  currency  The currency symbol 
  # @param character  kind  Instrument kind, if not provided instruments of all kinds are considered  (optional)
  # @param character  expired  Set to true to show expired instruments instead of active ones.  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetLastSettlementsByCurrencyGet", {
  # tests for PublicGetLastSettlementsByCurrencyGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves historical settlement, delivery and bankruptcy events coming from all instruments within given currency.
  # @param character  currency  The currency symbol 
  # @param character  type  Settlement type  (optional)
  # @param integer  count  Number of requested items, default - `20`  (optional)
  # @param character  continuation  Continuation token for pagination  (optional)
  # @param integer  search.start.timestamp  The latest timestamp to return result for  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetLastSettlementsByInstrumentGet", {
  # tests for PublicGetLastSettlementsByInstrumentGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves historical public settlement, delivery and bankruptcy events filtered by instrument name.
  # @param character  instrument.name  Instrument name 
  # @param character  type  Settlement type  (optional)
  # @param integer  count  Number of requested items, default - `20`  (optional)
  # @param character  continuation  Continuation token for pagination  (optional)
  # @param integer  search.start.timestamp  The latest timestamp to return result for  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetLastTradesByCurrencyAndTimeGet", {
  # tests for PublicGetLastTradesByCurrencyAndTimeGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest trades that have occurred for instruments in a specific currency symbol and within given time range.
  # @param character  currency  The currency symbol 
  # @param integer  start.timestamp  The earliest timestamp to return result for 
  # @param integer  end.timestamp  The most recent timestamp to return result for 
  # @param character  kind  Instrument kind, if not provided instruments of all kinds are considered  (optional)
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param character  include.old  Include trades older than 7 days, default - `false`  (optional)
  # @param character  sorting  Direction of results sorting (`default` value means no sorting, results will be returned in order in which they left the database)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetLastTradesByCurrencyGet", {
  # tests for PublicGetLastTradesByCurrencyGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest trades that have occurred for instruments in a specific currency symbol.
  # @param character  currency  The currency symbol 
  # @param character  kind  Instrument kind, if not provided instruments of all kinds are considered  (optional)
  # @param character  start.id  The ID number of the first trade to be returned  (optional)
  # @param character  end.id  The ID number of the last trade to be returned  (optional)
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param character  include.old  Include trades older than 7 days, default - `false`  (optional)
  # @param character  sorting  Direction of results sorting (`default` value means no sorting, results will be returned in order in which they left the database)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetLastTradesByInstrumentAndTimeGet", {
  # tests for PublicGetLastTradesByInstrumentAndTimeGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest trades that have occurred for a specific instrument and within given time range.
  # @param character  instrument.name  Instrument name 
  # @param integer  start.timestamp  The earliest timestamp to return result for 
  # @param integer  end.timestamp  The most recent timestamp to return result for 
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param character  include.old  Include trades older than 7 days, default - `false`  (optional)
  # @param character  sorting  Direction of results sorting (`default` value means no sorting, results will be returned in order in which they left the database)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetLastTradesByInstrumentGet", {
  # tests for PublicGetLastTradesByInstrumentGet
  # base path: https://www.deribit.com/api/v2
  # Retrieve the latest trades that have occurred for a specific instrument.
  # @param character  instrument.name  Instrument name 
  # @param integer  start.seq  The sequence number of the first trade to be returned  (optional)
  # @param integer  end.seq  The sequence number of the last trade to be returned  (optional)
  # @param integer  count  Number of requested items, default - `10`  (optional)
  # @param character  include.old  Include trades older than 7 days, default - `false`  (optional)
  # @param character  sorting  Direction of results sorting (`default` value means no sorting, results will be returned in order in which they left the database)  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetOrderBookGet", {
  # tests for PublicGetOrderBookGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves the order book, along with other market values for a given instrument.
  # @param character  instrument.name  The instrument name for which to retrieve the order book, see [`getinstruments`](#getinstruments) to obtain instrument names. 
  # @param numeric  depth  The number of entries to return for bids and asks.  (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetTradeVolumesGet", {
  # tests for PublicGetTradeVolumesGet
  # base path: https://www.deribit.com/api/v2
  # Retrieves aggregated 24h trade volumes for different instrument types and currencies.
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicGetTradingviewChartDataGet", {
  # tests for PublicGetTradingviewChartDataGet
  # base path: https://www.deribit.com/api/v2
  # Publicly available market data used to generate a TradingView candle chart.
  # @param character  instrument.name  Instrument name 
  # @param integer  start.timestamp  The earliest timestamp to return result for 
  # @param integer  end.timestamp  The most recent timestamp to return result for 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PublicTickerGet", {
  # tests for PublicTickerGet
  # base path: https://www.deribit.com/api/v2
  # Get ticker for an instrument.
  # @param character  instrument.name  Instrument name 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

