# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrderIdInitialMarginPair")

model.instance <- OrderIdInitialMarginPair$new()

test_that("order_id", {
  # tests for the property `order_id` (character)
  # Unique order identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`order_id`, "EXPECTED_RESULT")
})

test_that("initial_margin", {
  # tests for the property `initial_margin` (numeric)
  # Initial margin of order, in base currency

  # uncomment below to test the property 
  #expect_equal(model.instance$`initial_margin`, "EXPECTED_RESULT")
})

