# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Portfolio")

model.instance <- Portfolio$new()

test_that("eth", {
  # tests for the property `eth` (PortfolioEth)

  # uncomment below to test the property 
  #expect_equal(model.instance$`eth`, "EXPECTED_RESULT")
})

test_that("btc", {
  # tests for the property `btc` (PortfolioEth)

  # uncomment below to test the property 
  #expect_equal(model.instance$`btc`, "EXPECTED_RESULT")
})

