-module(openapi_order).

-export([encode/1]).

-export_type([openapi_order/0]).

-type openapi_order() ::
    #{ 'direction' := binary(),
       'reduce_only' => boolean(),
       'triggered' => boolean(),
       'order_id' := binary(),
       'price' := integer(),
       'time_in_force' := binary(),
       'api' := boolean(),
       'order_state' := binary(),
       'implv' => integer(),
       'advanced' => binary(),
       'post_only' := boolean(),
       'usd' => integer(),
       'stop_price' => integer(),
       'order_type' := binary(),
       'last_update_timestamp' := integer(),
       'original_order_type' => binary(),
       'max_show' := integer(),
       'profit_loss' => integer(),
       'is_liquidation' := boolean(),
       'filled_amount' => integer(),
       'label' := binary(),
       'commission' => integer(),
       'amount' => integer(),
       'trigger' => binary(),
       'instrument_name' => binary(),
       'creation_timestamp' := integer(),
       'average_price' => integer()
     }.

encode(#{ 'direction' := Direction,
          'reduce_only' := ReduceOnly,
          'triggered' := Triggered,
          'order_id' := OrderId,
          'price' := Price,
          'time_in_force' := TimeInForce,
          'api' := Api,
          'order_state' := OrderState,
          'implv' := Implv,
          'advanced' := Advanced,
          'post_only' := PostOnly,
          'usd' := Usd,
          'stop_price' := StopPrice,
          'order_type' := OrderType,
          'last_update_timestamp' := LastUpdateTimestamp,
          'original_order_type' := OriginalOrderType,
          'max_show' := MaxShow,
          'profit_loss' := ProfitLoss,
          'is_liquidation' := IsLiquidation,
          'filled_amount' := FilledAmount,
          'label' := Label,
          'commission' := Commission,
          'amount' := Amount,
          'trigger' := Trigger,
          'instrument_name' := InstrumentName,
          'creation_timestamp' := CreationTimestamp,
          'average_price' := AveragePrice
        }) ->
    #{ 'direction' => Direction,
       'reduce_only' => ReduceOnly,
       'triggered' => Triggered,
       'order_id' => OrderId,
       'price' => Price,
       'time_in_force' => TimeInForce,
       'api' => Api,
       'order_state' => OrderState,
       'implv' => Implv,
       'advanced' => Advanced,
       'post_only' => PostOnly,
       'usd' => Usd,
       'stop_price' => StopPrice,
       'order_type' => OrderType,
       'last_update_timestamp' => LastUpdateTimestamp,
       'original_order_type' => OriginalOrderType,
       'max_show' => MaxShow,
       'profit_loss' => ProfitLoss,
       'is_liquidation' => IsLiquidation,
       'filled_amount' => FilledAmount,
       'label' => Label,
       'commission' => Commission,
       'amount' => Amount,
       'trigger' => Trigger,
       'instrument_name' => InstrumentName,
       'creation_timestamp' => CreationTimestamp,
       'average_price' => AveragePrice
     }.
